// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthO0Oun-4UaNZA-8WjYI-g8tMRXmb66g',
    appId: '1:83108278035:web:f9386c2881b616077034e6',
    messagingSenderId: '83108278035',
    projectId: 'chatboard-52d74',
    authDomain: 'chatboard-52d74.firebaseapp.com',
    storageBucket: 'chatboard-52d74.firebasestorage.app',
    measurementId: 'G-BZB3CGGY5H',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBthO0Oun-4UaNZA-8WjYI-g8tMRXmb66g',
    appId: '1:83108278035:web:2bbfe6a826f481737034e6',
    messagingSenderId: '83108278035',
    projectId: 'chatboard-52d74',
    authDomain: 'chatboard-52d74.firebaseapp.com',
    storageBucket: 'chatboard-52d74.firebasestorage.app',
    measurementId: 'G-NHTGGJT3P9',
  );

}